# Configures builds for all branches and deployment on the "prod" branch.

language: node_js
node_js: node

# TODO: If deployment becomes unreliable, use a package-lock.json and npm ci
install: npm install
script: npm run build

deploy:
  provider: firebase
  skip-cleanup: true
  on:
    branch: prod
  token:
    secure: uVCgRFWjbYjEtW0t4MNUi7PpD9YUTwyiYXaW7mXW6CV2B5gf+T0MztRMnzxwFnMiZXiuNqQGNJfSsKbZw8me0YNE7K64Nhzx1Db7AHp+yfgILkjf/DNJEbhbJ3VAcQqpxK2wOsV6FTv/d0/lDb2xfPNgLJegaYCtmc/LfJA+veRMWGMS0jfToiL/HfLGoitR/76C2dEJsZ5l8yyOTsE3do58ige/jPWpfzQuTux325vpusxdWxkXQ7a36LrJb6+K6FVwGdzwt7yG+k4MK49WJcpnTDwbIPBgWf57O+r3ZK64gLpbaj80EnSyJiPnTj9l3PC4Afd18KHtGZvuXgtsnD+BMDd/cRTuDS9dVFbPDtyTr9oJtgafnIS0nAFNY6XwIcCkX6F4FCIUCEQznZsFfYO9fSUw/jO2+aG0G3Enlrg5KOzjs/xg3tfqMLtT1xMT8rUDRpTz8qe0gaKUoo/3aswEr5abRJEcBdELakAamYwEK0bnnnGRexYTkymOmOh3ka2Amav++7pZRr8TsSCqo2ml+VqcstrDoB+h9iovJGrmNu4J3vKqO+bqvd6BIHGHc+WyloEvouXKBG30sEi6mYsvRgw9VyoJoNV/6ASPIpST40aGjPrt6s0psj17qAYkl5AnCaJ1ltp3GB8yQvjYTiFRHdNAWHimMPuPJLlYI/Y=
  
env:
  global:
    # TODO: Remove once warnings are fixed at head.
    - CI=false
